import { StyleSheet, Dimensions } from "react-native";
import { lightTheme } from "@/features/theme/ThemeContext";

type Theme = typeof lightTheme;

const { width: screenWidth } = Dimensions.get("window");

export const createStyles = (theme: Theme) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.background,
    },
    mainContent: {
      flex: 1,
    },
    scrollContent: {
      flexGrow: 1,
      paddingBottom: 20,
    },
    // Header styles
    header: {
      backgroundColor: theme.headerGradient,
      paddingTop: 10,
      paddingHorizontal: 20,
      paddingBottom: 15,
      borderBottomLeftRadius: 25,
      borderBottomRightRadius: 25,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.15,
      shadowRadius: 10,
      elevation: 8,
    },
    headerContent: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    headerTitle: {
      fontSize: 24,
      fontWeight: "bold",
      color: "#fff",
      textAlign: "right",
      flex: 1,
    },
    menuButton: {
      backgroundColor: "rgba(255,255,255,0.2)",
      borderRadius: 12,
      padding: 12,
      marginLeft: 15,
    },
    menuIcon: {
      fontSize: 20,
      color: "#fff",
      fontWeight: "bold",
    },
    // Section styles
    sectionTitle: {
      fontSize: 20,
      fontWeight: "bold",
      color: theme.text,
      marginBottom: 15,
      textAlign: "right",
    },
    // Social section
    socialSection: {
      backgroundColor: theme.surface,
      borderRadius: 16,
      padding: 20,
      margin: 20,
      marginTop: 15,
      marginBottom: 15,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
      elevation: 3,
    },
    socialTabs: {
      flexDirection: "row",
      backgroundColor: "#f8f9fa",
      borderRadius: 15,
      marginBottom: 20,
      overflow: "hidden",
    },
    socialTab: {
      flex: 1,
      paddingVertical: 12,
      paddingHorizontal: 6,
      alignItems: "center",
      backgroundColor: "transparent",
      minWidth: 0,
    },
    activeSocialTab: {
      backgroundColor: "#667eea",
    },
    socialTabText: {
      fontSize: 12,
      color: "#7f8c8d",
      fontWeight: "600",
      textAlign: "center",
      flexShrink: 1,
    },
    activeSocialTabText: {
      color: "#fff",
      fontWeight: "bold",
    },
    socialContent: {
      minHeight: 200,
    },
    searchInput: {
      borderWidth: 1,
      borderColor: "#e0e0e0",
      borderRadius: 12,
      padding: 15,
      fontSize: 16,
      marginBottom: 15,
      textAlign: "right",
      backgroundColor: "#f8f9fa",
    },
    userList: {
      maxHeight: 300,
    },
    userItem: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingVertical: 12,
      borderBottomWidth: 1,
      borderBottomColor: "#f0f0f0",
    },
    userInfo: {
      flexDirection: "row",
      alignItems: "center",
      flex: 1,
    },
    socialAvatar: {
      width: 35,
      height: 35,
      borderRadius: 17.5,
      marginLeft: 12,
      borderWidth: 2,
      borderColor: "#667eea",
    },
    userName: {
      fontSize: 16,
      color: "#2c3e50",
      flex: 1,
      textAlign: "right",
      fontWeight: "500",
    },
    followButton: {
      backgroundColor: "#667eea",
      paddingHorizontal: 15,
      paddingVertical: 8,
      borderRadius: 20,
    },
    unfollowButton: {
      backgroundColor: "#e74c3c",
    },
    followButtonText: {
      color: "#fff",
      fontSize: 13,
      fontWeight: "600",
      textAlign: "center",
    },
    unfollowButtonText: {
      color: "#fff",
    },
    // Side panel styles
    overlay: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: "rgba(0,0,0,0.5)",
      zIndex: 998,
    },
    sidePanel: {
      position: "absolute",
      top: 0,
      bottom: 0,
      width: screenWidth * 0.8,
      backgroundColor: theme.surface,
      zIndex: 999,
      shadowColor: theme.shadow,
      shadowOffset: { width: -3, height: 0 },
      shadowOpacity: 0.3,
      shadowRadius: 10,
      elevation: 15,
    },
    sidePanelContent: {
      flex: 1,
      padding: 20,
      paddingTop: 10,
    },
    sidePanelScrollContent: {
      flexGrow: 1,
      paddingBottom: 50,
    },
    sidePanelHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 20,
      paddingTop: 20,
    },
    sidePanelTitle: {
      fontSize: 22,
      fontWeight: "bold",
      color: theme.text,
      flex: 1,
      textAlign: "right",
    },
    closeButton: {
      backgroundColor: "#f8f9fa",
      borderRadius: 20,
      width: 35,
      height: 35,
      justifyContent: "center",
      alignItems: "center",
      marginLeft: 15,
    },
    closeButtonText: {
      fontSize: 18,
      color: "#7f8c8d",
      fontWeight: "bold",
    },
    // Avatar section in side panel
    avatarSection: {
      alignItems: "center",
      marginBottom: 25,
      paddingVertical: 15,
      backgroundColor: "#f8f9fa",
      borderRadius: 15,
    },
    sideAvatar: {
      width: 80,
      height: 80,
      borderRadius: 40,
      backgroundColor: "#eee",
      borderWidth: 3,
      borderColor: "#667eea",
    },
    avatarOverlay: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: "rgba(0,0,0,0.5)",
      borderRadius: 40,
      justifyContent: "center",
      alignItems: "center",
    },
    avatarButtons: {
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
      gap: 15,
      marginTop: 10,
    },
    editPhoto: {
      color: "#667eea",
      fontWeight: "600",
      textAlign: "center",
      fontSize: 14,
    },
    removePhoto: {
      color: "#e74c3c",
      fontWeight: "600",
      textAlign: "center",
      fontSize: 14,
    },
    // Profile edit section
    profileEditSection: {
      marginBottom: 25,
    },
    fieldLabel: {
      fontSize: 14,
      color: "#7f8c8d",
      marginBottom: 5,
      textAlign: "right",
      fontWeight: "600",
    },
    fieldValue: {
      fontSize: 16,
      color: "#2c3e50",
      marginBottom: 15,
      textAlign: "right",
      padding: 10,
      backgroundColor: "#f8f9fa",
      borderRadius: 8,
      borderWidth: 1,
      borderColor: "#e0e0e0",
    },
    sideInput: {
      borderWidth: 1,
      borderColor: "#e0e0e0",
      borderRadius: 8,
      padding: 12,
      fontSize: 16,
      marginBottom: 15,
      textAlign: "right",
      backgroundColor: "#fff",
    },
    editButton: {
      backgroundColor: "#667eea",
      paddingVertical: 12,
      paddingHorizontal: 20,
      borderRadius: 10,
      alignItems: "center",
    },
    saveButton: {
      backgroundColor: "#27ae60",
      paddingVertical: 12,
      paddingHorizontal: 20,
      borderRadius: 10,
      alignItems: "center",
    },
    buttonText: {
      color: "#fff",
      fontWeight: "600",
      fontSize: 16,
    },
    // Preferences section
    preferencesSection: {
      marginBottom: 25,
    },
    preferencesSubtitle: {
      fontSize: 14,
      color: "#7f8c8d",
      marginBottom: 15,
      textAlign: "right",
    },
    circleSizeColumn: {
      gap: 10,
    },
    circleSizeRow: {
      flexDirection: "row",
      alignItems: "center",
      padding: 15,
      borderRadius: 12,
      backgroundColor: "#f8f9fa",
      borderWidth: 2,
      borderColor: "transparent",
    },
    circleSizeRowSelected: {
      backgroundColor: "#e8f4fd",
      borderColor: "#667eea",
    },
    circleSizeRowContent: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      width: "100%",
    },
    circleSizeRowLabel: {
      fontSize: 16,
      color: "#7f8c8d",
      fontWeight: "600",
      flex: 1,
      textAlign: "right",
    },
    circleSizeRowLabelSelected: {
      color: "#667eea",
      fontWeight: "bold",
    },
    circleSizeRowPreview: {
      justifyContent: "center",
      alignItems: "center",
      marginLeft: 15,
    },
    circleSizePreviewText: {
      color: "white",
      fontWeight: "bold",
    },
    // Statistics section
    statsSection: {
      backgroundColor: "#fff",
      margin: 20,
      marginTop: 0,
      borderRadius: 20,
      padding: 20,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
      elevation: 5,
    },
    statsGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      justifyContent: "space-between",
    },
    statCard: {
      backgroundColor: "#f8f9fa",
      borderRadius: 15,
      padding: 15,
      alignItems: "center",
      width: "48%",
      marginBottom: 12,
      borderLeftWidth: 4,
      borderLeftColor: "#667eea",
    },
    statNumber: {
      fontSize: 24,
      fontWeight: "bold",
      color: "#2c3e50",
      marginBottom: 4,
    },
    statLabel: {
      fontSize: 12,
      color: "#7f8c8d",
      textAlign: "center",
      fontWeight: "600",
    },
    // Admin section
    adminSection: {
      backgroundColor: "#fff",
      margin: 20,
      marginTop: 0,
      borderRadius: 20,
      padding: 20,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
      elevation: 5,
      borderWidth: 2,
      borderColor: "#e74c3c",
    },
    adminTitle: {
      fontSize: 18,
      fontWeight: "bold",
      color: "#e74c3c",
      marginBottom: 15,
      textAlign: "right",
    },
    adminButtons: {
      gap: 10,
    },
    adminButton: {
      backgroundColor: "#e74c3c",
      paddingVertical: 12,
      paddingHorizontal: 15,
      borderRadius: 10,
      alignItems: "center",
    },
    adminButtonText: {
      color: "#fff",
      fontWeight: "600",
      fontSize: 14,
    },
    privacyButton: {
      backgroundColor: "#f39c12",
    },
    // Loading and empty states
    loadingText: {
      fontSize: 16,
      color: "#7f8c8d",
      textAlign: "center",
      padding: 20,
    },
    emptyText: {
      fontSize: 16,
      color: "#7f8c8d",
      textAlign: "center",
      padding: 30,
      fontStyle: "italic",
    },
    errorText: {
      fontSize: 16,
      color: "#e74c3c",
      textAlign: "center",
      padding: 20,
    },
    statsContainer: {
      backgroundColor: theme.surface,
      borderRadius: 16,
      padding: 20,
      margin: 20,
      marginTop: 0,
      marginBottom: 20,
      shadowColor: theme.shadow,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
      elevation: 3,
    },
    statsTitle: {
      fontSize: 20,
      fontWeight: "bold",
      color: theme.text,
      flex: 1,
    },
    statsHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: 20,
    },
    // Modal styles
    modalContainer: {
      flex: 1,
      backgroundColor: "rgba(0, 0, 0, 0.5)",
      justifyContent: "center",
      alignItems: "center",
    },
    modalContent: {
      backgroundColor: "#fff",
      borderRadius: 20,
      padding: 25,
      margin: 20,
      maxHeight: "80%",
      width: "90%",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.25,
      shadowRadius: 12,
      elevation: 8,
    },
    modalHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 20,
      paddingBottom: 15,
      borderBottomWidth: 1,
      borderBottomColor: "#f0f0f0",
    },
    modalTitle: {
      fontSize: 20,
      fontWeight: "bold",
      color: "#2c3e50",
      flex: 1,
      textAlign: "right",
    },
    modalCloseButton: {
      width: 30,
      height: 30,
      borderRadius: 15,
      backgroundColor: "#f8f9fa",
      justifyContent: "center",
      alignItems: "center",
      marginLeft: 10,
    },
    modalCloseText: {
      fontSize: 18,
      color: "#7f8c8d",
      fontWeight: "bold",
    },
    overallStatsContainer: {
      backgroundColor: "#667eea",
      borderRadius: 12,
      padding: 16,
      marginBottom: 20,
      alignItems: "center",
    },
    overallStatsText: {
      fontSize: 16,
      fontWeight: "bold",
      color: "#fff",
      textAlign: "center",
    },
    gradeStatRow: {
      marginBottom: 15,
    },
    gradeStatHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 8,
    },
    gradeLabel: {
      fontSize: 16,
      fontWeight: "bold",
      color: "#2c3e50",
    },
    gradePercentage: {
      fontSize: 16,
      fontWeight: "bold",
      color: "#667eea",
    },
    progressBarContainer: {
      height: 8,
      backgroundColor: "#f0f0f0",
      borderRadius: 4,
      marginBottom: 5,
    },
    progressBar: {
      height: "100%",
      borderRadius: 4,
    },
    gradeStatDetails: {
      fontSize: 12,
      color: "#7f8c8d",
      textAlign: "center",
    },
    joinDateContainer: {
      backgroundColor: "#e8f4f8",
      padding: 12,
      borderRadius: 8,
      marginTop: 10,
    },
    joinDateText: {
      fontSize: 14,
      color: "#2c3e50",
      textAlign: "right",
      fontWeight: "500",
    },
    joinDateContent: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    joinDatePrivacy: {
      flexDirection: "row",
      alignItems: "center",
    },
    privacyToggleContainer: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginTop: 10,
    },
    privacyToggleLabel: {
      fontSize: 12,
      color: "#7f8c8d",
    },
    privacySwitch: {
      transform: [{ scaleX: 0.8 }, { scaleY: 0.8 }],
    },
    privacyEditNotification: {
      backgroundColor: "#fff3cd",
      borderColor: "#ffeaa7",
      borderWidth: 1,
      borderRadius: 8,
      padding: 12,
      marginBottom: 15,
    },
    privacyEditText: {
      fontSize: 14,
      color: "#856404",
      textAlign: "center",
    },
    headerButtons: {
      flexDirection: "row",
      alignItems: "center",
    },
    editButtonActive: {
      backgroundColor: "#27ae60",
    },
    editButtonTextActive: {
      color: "#fff",
    },
    statContent: {
      flexDirection: "row",
      alignItems: "center",
    },
    statIcon: {
      fontSize: 24,
      marginRight: 12,
    },
    statTextContainer: {
      flex: 1,
    },
    statValue: {
      fontSize: 18,
      fontWeight: "bold",
      color: "#2c3e50",
    },
    statTitle: {
      fontSize: 12,
      color: "#7f8c8d",
      marginTop: 2,
    },
    statArrow: {
      fontSize: 20,
      color: "#8e44ad",
      fontWeight: "bold",
      marginLeft: 8,
    },
    themeToggleContainer: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: 20,
    },
    themeOption: {
      flex: 1,
    },
    themeOptionLabel: {
      fontSize: 14,
      color: "#7f8c8d",
      textAlign: "center",
    },
    themeOptionLabelSelected: {
      color: theme.text,
      fontWeight: "bold",
    },
    themeToggle: {
      width: 60,
      height: 30,
      borderRadius: 15,
      backgroundColor: theme.card,
      borderWidth: 2,
      borderColor: theme.border,
      justifyContent: "center",
      padding: 2,
      marginHorizontal: 15,
    },
    themeToggleDark: {
      backgroundColor: theme.primary,
    },
    themeToggleThumb: {
      width: 26,
      height: 26,
      backgroundColor: "#fff",
      borderRadius: 13,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 2,
      elevation: 3,
      alignSelf: "flex-start",
    },
    themeToggleThumbDark: {
      alignSelf: "flex-end",
    },
    logoutButton: {
      backgroundColor: "#e74c3c",
      paddingVertical: 15,
      paddingHorizontal: 30,
      borderRadius: 12,
      alignItems: "center",
      marginTop: 20,
    },
    logoutButtonText: {
      color: "#fff",
      fontSize: 16,
      fontWeight: "bold",
    },
  });
