import { StyleSheet, Dimensions } from "react-native";
import { lightTheme } from "@/features/theme/ThemeContext";

type Theme = typeof lightTheme;

const { width: screenWidth } = Dimensions.get("window");

export const createStyles = (theme: Theme) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.background,
    },
    mainContent: {
      flex: 1,
    },
    scrollContent: {
      flexGrow: 1,
      paddingBottom: 20,
    },
    // Header styles
    header: {
      backgroundColor: theme.headerGradient,
      paddingTop: 10,
      paddingHorizontal: 20,
      paddingBottom: 15,
      borderBottomLeftRadius: 25,
      borderBottomRightRadius: 25,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.15,
      shadowRadius: 10,
      elevation: 8,
    },
    headerContent: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    headerTitle: {
      fontSize: 24,
      fontWeight: "bold",
      color: "#fff",
      textAlign: "right",
      flex: 1,
    },
    menuButton: {
      backgroundColor: "rgba(255,255,255,0.2)",
      borderRadius: 12,
      padding: 12,
      marginLeft: 15,
    },
    menuIcon: {
      fontSize: 20,
      color: "#fff",
      fontWeight: "bold",
    },
    // Section styles
    sectionTitle: {
      fontSize: 20,
      fontWeight: "bold",
      color: theme.text,
      marginBottom: 15,
      textAlign: "right",
    },
    // Social section
    socialSection: {
      backgroundColor: theme.surface,
      borderRadius: 20,
      padding: 20,
      margin: 20,
      marginTop: 15,
      marginBottom: 15,
      shadowColor: theme.shadow,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.12,
      shadowRadius: 12,
      elevation: 5,
    },
    socialTabs: {
      flexDirection: "row",
      backgroundColor: theme.card,
      borderRadius: 15,
      marginBottom: 20,
      overflow: "hidden",
      padding: 4,
    },
    socialTab: {
      flex: 1,
      paddingVertical: 12,
      paddingHorizontal: 6,
      alignItems: "center",
      backgroundColor: "transparent",
      minWidth: 0,
      borderRadius: 12,
    },
    activeSocialTab: {
      backgroundColor: theme.primary,
    },
    socialTabText: {
      fontSize: 12,
      color: theme.textSecondary,
      fontWeight: "600",
      textAlign: "center",
      flexShrink: 1,
    },
    activeSocialTabText: {
      color: "#fff",
      fontWeight: "bold",
    },
    socialContent: {
      minHeight: 200,
    },
    searchInput: {
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: 12,
      padding: 15,
      fontSize: 16,
      marginBottom: 15,
      textAlign: "right",
      backgroundColor: theme.inputBackground,
      color: theme.text,
    },
    userList: {
      maxHeight: 300,
    },
    userItem: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingVertical: 12,
      borderBottomWidth: 1,
      borderBottomColor: theme.border,
    },
    userInfo: {
      flexDirection: "row",
      alignItems: "center",
      flex: 1,
    },
    socialAvatar: {
      width: 40,
      height: 40,
      borderRadius: 20,
      marginLeft: 12,
      borderWidth: 2,
      borderColor: theme.primary,
    },
    userName: {
      fontSize: 16,
      color: theme.text,
      flex: 1,
      textAlign: "right",
      fontWeight: "500",
    },
    followButton: {
      backgroundColor: theme.primary,
      paddingHorizontal: 18,
      paddingVertical: 10,
      borderRadius: 20,
    },
    unfollowButton: {
      backgroundColor: theme.error,
    },
    followButtonText: {
      color: "#fff",
      fontSize: 13,
      fontWeight: "600",
      textAlign: "center",
    },
    unfollowButtonText: {
      color: "#fff",
    },
    // Side panel styles
    overlay: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: "rgba(0,0,0,0.5)",
      zIndex: 998,
    },
    sidePanel: {
      position: "absolute",
      top: 0,
      bottom: 0,
      width: screenWidth * 0.8,
      backgroundColor: theme.surface,
      zIndex: 999,
      shadowColor: theme.shadow,
      shadowOffset: { width: -3, height: 0 },
      shadowOpacity: 0.3,
      shadowRadius: 10,
      elevation: 15,
    },
    sidePanelContent: {
      flex: 1,
      padding: 20,
      paddingTop: 10,
    },
    sidePanelScrollContent: {
      flexGrow: 1,
      paddingBottom: 50,
    },
    sidePanelHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 20,
      paddingTop: 20,
    },
    sidePanelTitle: {
      fontSize: 22,
      fontWeight: "bold",
      color: theme.text,
      flex: 1,
      textAlign: "right",
    },
    closeButton: {
      backgroundColor: theme.card,
      borderRadius: 20,
      width: 40,
      height: 40,
      justifyContent: "center",
      alignItems: "center",
      marginLeft: 15,
    },
    closeButtonText: {
      fontSize: 18,
      color: theme.textSecondary,
      fontWeight: "bold",
    },
    // Avatar section in side panel
    avatarSection: {
      alignItems: "center",
      marginBottom: 25,
      paddingVertical: 20,
      backgroundColor: theme.card,
      borderRadius: 20,
    },
    sideAvatar: {
      width: 90,
      height: 90,
      borderRadius: 45,
      backgroundColor: theme.border,
      borderWidth: 4,
      borderColor: theme.primary,
    },
    avatarOverlay: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: "rgba(0,0,0,0.5)",
      borderRadius: 40,
      justifyContent: "center",
      alignItems: "center",
    },
    avatarButtons: {
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
      gap: 15,
      marginTop: 12,
    },
    editPhoto: {
      color: theme.primary,
      fontWeight: "700",
      textAlign: "center",
      fontSize: 14,
    },
    removePhoto: {
      color: theme.error,
      fontWeight: "600",
      textAlign: "center",
      fontSize: 14,
    },
    // Profile edit section
    profileEditSection: {
      marginBottom: 25,
      backgroundColor: theme.card,
      borderRadius: 16,
      padding: 16,
    },
    fieldLabel: {
      fontSize: 14,
      color: theme.textSecondary,
      marginBottom: 8,
      textAlign: "right",
      fontWeight: "600",
    },
    fieldValue: {
      fontSize: 16,
      color: theme.text,
      marginBottom: 15,
      textAlign: "right",
      padding: 12,
      backgroundColor: theme.inputBackground,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: theme.border,
    },
    sideInput: {
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: 10,
      padding: 12,
      fontSize: 16,
      marginBottom: 15,
      textAlign: "right",
      backgroundColor: theme.inputBackground,
      color: theme.text,
    },
    editButton: {
      backgroundColor: theme.primary,
      paddingVertical: 14,
      paddingHorizontal: 20,
      borderRadius: 12,
      alignItems: "center",
    },
    saveButton: {
      backgroundColor: theme.success,
      paddingVertical: 14,
      paddingHorizontal: 20,
      borderRadius: 12,
      alignItems: "center",
    },
    buttonText: {
      color: "#fff",
      fontWeight: "700",
      fontSize: 16,
    },
    // Preferences section
    preferencesSection: {
      marginBottom: 25,
      backgroundColor: theme.card,
      borderRadius: 16,
      padding: 16,
    },
    preferencesSubtitle: {
      fontSize: 14,
      color: theme.textSecondary,
      marginBottom: 15,
      textAlign: "right",
    },
    circleSizeColumn: {
      gap: 10,
    },
    circleSizeRow: {
      flexDirection: "row",
      alignItems: "center",
      padding: 15,
      borderRadius: 12,
      backgroundColor: theme.inputBackground,
      borderWidth: 2,
      borderColor: "transparent",
    },
    circleSizeRowSelected: {
      backgroundColor: theme.isDark ? "rgba(102, 126, 234, 0.2)" : "#e8f4fd",
      borderColor: theme.primary,
    },
    circleSizeRowContent: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      width: "100%",
    },
    circleSizeRowLabel: {
      fontSize: 16,
      color: theme.textSecondary,
      fontWeight: "600",
      flex: 1,
      textAlign: "right",
    },
    circleSizeRowLabelSelected: {
      color: theme.primary,
      fontWeight: "bold",
    },
    circleSizeRowPreview: {
      justifyContent: "center",
      alignItems: "center",
      marginLeft: 15,
    },
    circleSizePreviewText: {
      color: "white",
      fontWeight: "bold",
    },
    // Statistics section
    statsSection: {
      backgroundColor: theme.surface,
      margin: 20,
      marginTop: 0,
      borderRadius: 20,
      padding: 20,
      shadowColor: theme.shadow,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.12,
      shadowRadius: 12,
      elevation: 5,
    },
    statsGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      justifyContent: "space-between",
    },
    statCard: {
      backgroundColor: theme.card,
      borderRadius: 16,
      padding: 16,
      alignItems: "center",
      width: "48%",
      marginBottom: 12,
      borderLeftWidth: 4,
      borderLeftColor: theme.primary,
    },
    statNumber: {
      fontSize: 24,
      fontWeight: "bold",
      color: theme.text,
      marginBottom: 4,
    },
    statLabel: {
      fontSize: 12,
      color: theme.textSecondary,
      textAlign: "center",
      fontWeight: "600",
    },
    // Admin section
    adminSection: {
      backgroundColor: theme.surface,
      margin: 20,
      marginTop: 0,
      borderRadius: 20,
      padding: 20,
      shadowColor: theme.shadow,
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
      elevation: 5,
      borderWidth: 2,
      borderColor: theme.error,
    },
    adminTitle: {
      fontSize: 18,
      fontWeight: "bold",
      color: theme.error,
      marginBottom: 15,
      textAlign: "right",
    },
    adminButtons: {
      gap: 10,
    },
    adminButton: {
      backgroundColor: theme.error,
      paddingVertical: 14,
      paddingHorizontal: 15,
      borderRadius: 12,
      alignItems: "center",
    },
    adminButtonText: {
      color: "#fff",
      fontWeight: "700",
      fontSize: 14,
    },
    adminModeRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingVertical: 12,
      borderBottomWidth: 1,
      borderBottomColor: theme.border,
      marginBottom: 10,
    },
    adminModeLabel: {
      fontSize: 16,
      color: theme.text,
      fontWeight: "500",
    },
    adminModeHint: {
      fontSize: 12,
      color: theme.success,
      textAlign: "right",
      marginBottom: 15,
      fontStyle: "italic",
    },
    privacyButton: {
      backgroundColor: theme.warning,
    },
    // Loading and empty states
    loadingText: {
      fontSize: 16,
      color: theme.textSecondary,
      textAlign: "center",
      padding: 20,
    },
    emptyText: {
      fontSize: 16,
      color: theme.textSecondary,
      textAlign: "center",
      padding: 30,
      fontStyle: "italic",
    },
    errorText: {
      fontSize: 16,
      color: theme.error,
      textAlign: "center",
      padding: 20,
    },
    statsContainer: {
      backgroundColor: theme.surface,
      borderRadius: 16,
      padding: 20,
      margin: 20,
      marginTop: 0,
      marginBottom: 20,
      shadowColor: theme.shadow,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
      elevation: 3,
    },
    statsTitle: {
      fontSize: 20,
      fontWeight: "bold",
      color: theme.text,
      flex: 1,
    },
    statsHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: 20,
    },
    // Modal styles
    modalContainer: {
      flex: 1,
      backgroundColor: theme.overlay,
      justifyContent: "center",
      alignItems: "center",
    },
    modalContent: {
      backgroundColor: theme.modalBackground,
      borderRadius: 24,
      padding: 25,
      margin: 20,
      maxHeight: "80%",
      width: "90%",
      shadowColor: theme.shadow,
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.25,
      shadowRadius: 16,
      elevation: 10,
    },
    modalHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 20,
      paddingBottom: 15,
      borderBottomWidth: 1,
      borderBottomColor: theme.border,
    },
    modalTitle: {
      fontSize: 20,
      fontWeight: "bold",
      color: theme.text,
      flex: 1,
      textAlign: "right",
    },
    modalCloseButton: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: theme.card,
      justifyContent: "center",
      alignItems: "center",
      marginLeft: 10,
    },
    modalCloseText: {
      fontSize: 18,
      color: theme.textSecondary,
      fontWeight: "bold",
    },
    overallStatsContainer: {
      backgroundColor: theme.primary,
      borderRadius: 16,
      padding: 18,
      marginBottom: 20,
      alignItems: "center",
    },
    overallStatsText: {
      fontSize: 16,
      fontWeight: "bold",
      color: "#fff",
      textAlign: "center",
    },
    gradeStatRow: {
      marginBottom: 15,
    },
    gradeStatHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 8,
    },
    gradeLabel: {
      fontSize: 16,
      fontWeight: "bold",
      color: theme.text,
    },
    gradePercentage: {
      fontSize: 16,
      fontWeight: "bold",
      color: theme.primary,
    },
    progressBarContainer: {
      height: 10,
      backgroundColor: theme.card,
      borderRadius: 5,
      marginBottom: 5,
    },
    progressBar: {
      height: "100%",
      borderRadius: 5,
    },
    gradeStatDetails: {
      fontSize: 12,
      color: theme.textSecondary,
      textAlign: "center",
    },
    joinDateContainer: {
      backgroundColor: theme.isDark ? "rgba(102, 126, 234, 0.15)" : "#e8f4f8",
      padding: 14,
      borderRadius: 12,
      marginTop: 10,
    },
    joinDateText: {
      fontSize: 14,
      color: theme.text,
      textAlign: "right",
      fontWeight: "500",
    },
    joinDateContent: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    joinDatePrivacy: {
      flexDirection: "row",
      alignItems: "center",
    },
    privacyToggleContainer: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginTop: 10,
    },
    privacyToggleLabel: {
      fontSize: 12,
      color: theme.textSecondary,
    },
    privacySwitch: {
      transform: [{ scaleX: 0.8 }, { scaleY: 0.8 }],
    },
    privacyEditNotification: {
      backgroundColor: theme.isDark ? "rgba(255, 193, 7, 0.15)" : "#fff3cd",
      borderColor: theme.warning,
      borderWidth: 1,
      borderRadius: 12,
      padding: 14,
      marginBottom: 15,
    },
    privacyEditText: {
      fontSize: 14,
      color: theme.isDark ? theme.warning : "#856404",
      textAlign: "center",
    },
    headerButtons: {
      flexDirection: "row",
      alignItems: "center",
    },
    editButtonActive: {
      backgroundColor: theme.success,
    },
    editButtonTextActive: {
      color: "#fff",
    },
    statContent: {
      flexDirection: "row",
      alignItems: "center",
    },
    statIcon: {
      fontSize: 28,
      marginRight: 14,
    },
    statTextContainer: {
      flex: 1,
    },
    statValue: {
      fontSize: 20,
      fontWeight: "bold",
      color: theme.text,
    },
    statTitle: {
      fontSize: 12,
      color: theme.textSecondary,
      marginTop: 2,
    },
    statArrow: {
      fontSize: 20,
      color: theme.secondary,
      fontWeight: "bold",
      marginLeft: 8,
    },
    themeToggleContainer: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: 20,
      backgroundColor: theme.card,
      borderRadius: 16,
      padding: 16,
    },
    themeOption: {
      flex: 1,
    },
    themeOptionLabel: {
      fontSize: 14,
      color: theme.textSecondary,
      textAlign: "center",
    },
    themeOptionLabelSelected: {
      color: theme.text,
      fontWeight: "bold",
    },
    themeToggle: {
      width: 64,
      height: 34,
      borderRadius: 17,
      backgroundColor: theme.card,
      borderWidth: 2,
      borderColor: theme.border,
      justifyContent: "center",
      padding: 2,
      marginHorizontal: 15,
    },
    themeToggleDark: {
      backgroundColor: theme.primary,
      borderColor: theme.primary,
    },
    themeToggleThumb: {
      width: 28,
      height: 28,
      backgroundColor: "#fff",
      borderRadius: 14,
      shadowColor: theme.shadow,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 3,
      elevation: 3,
      alignSelf: "flex-start",
    },
    themeToggleThumbDark: {
      alignSelf: "flex-end",
    },
    logoutButton: {
      backgroundColor: theme.error,
      paddingVertical: 16,
      paddingHorizontal: 30,
      borderRadius: 14,
      alignItems: "center",
      marginTop: 20,
    },
    logoutButtonText: {
      color: "#fff",
      fontSize: 16,
      fontWeight: "bold",
    },
  });
